debug: false
vm:
  log_file: vm_events.log
  max_instructions: 1000
  max_instructions_per_cycle: 1
  indices:
    attempt_modulus_idx: 10
    attempt_increment_idx: 1
    random_max_exclusive_idx_for_offset: 3
    max_failures_before_stuck_idx: 3
    stuck_signal_print_value_idx: 99
    modification_slot_0_addr_idx: 1
    modification_slot_1_addr_idx: 2
    uor_decision_build_push_idx: 0
    uor_decision_build_add_idx: 1
    uor_decision_build_nop_idx: 2
teacher:
  difficulty: MEDIUM
  alert_email: operator@example.com
prime_idx_success: 1
prime_idx_failure: 0
stuck_signal_print_value: "99"
streak_thresholds:
  quick_success_to_upgrade: 3
  struggle_to_downgrade: 2
difficulty_levels:
  EASY:
    range_max: 4
    max_attempts_before_struggle: 5
    quick_success_threshold: 1
  MEDIUM:
    range_max: 9
    max_attempts_before_struggle: 4
    quick_success_threshold: 1
  HARD:
    range_max: 14
    max_attempts_before_struggle: 3
    quick_success_threshold: 2
benchmark:
  iterations: 100

# Physics and quantum defaults
consciousness_physics:
  information_transfer_rate: 1e20
  consciousness_bandwidth: 1e22
  info_reality_bridge_bandwidth: 1e20
  info_reality_bridge_fidelity: 0.9

quantum:
  communication_bandwidth: 1e6
  teleportation_fidelity: 0.9
  fidelity_threshold: 0.99
  plan_step_duration_base: 0.1
  plan_energy_base: 1e9
  plan_energy_scale: 1e10

reality_interface:
  energy_limit: 1e50
  info_matter_bandwidth: 1e20
  info_matter_fidelity: 0.99

paths:
  log_dir: logs/
  results_dir: results/
  default_uor_program: goal_seeker_demo.uor.txt
  data_dir: data/
  countermeasures_file: data/akashic_countermeasures.json

# Scroll ID configuration so identifiers can be changed without touching code
scroll_ids:
  counter_control: 60
  cognitive_sovereignty: 54

cosmic:
  defaults:
    spatial_scale: 1e26  # placeholder cosmic scale (light years)
    temporal_scale: 1e100  # placeholder cosmic time units
    consciousness_scale: 1e50  # placeholder number of consciousnesses
    modification_energy_required: 1e60  # placeholder energy (joules)

# MCP (Model Context Protocol) configuration
mcp:
  enabled: true
  client:
    timeout: 30  # seconds
    max_connections: 10
    retry_attempts: 3
    connection_check_interval: 30  # seconds
  server:
    enabled: false  # Set to true to expose UOR Evolution as MCP server
    port: 8765
    exposed_capabilities:
      - consciousness_analysis
      - pattern_recognition
      - ethical_reasoning
      - philosophical_inquiry
      - cosmic_problem_synthesis
      - mathematical_consciousness
  trusted_servers:
    # Add trusted MCP server URLs here
    # Examples:
    # - "mcp://localhost:8766"
    # - "mcp://knowledge.example.com"
  tool_selection:
    # Weights for tool selection algorithm
    capability_weight: 0.4
    compatibility_weight: 0.3
    ethical_weight: 0.3
  consciousness_integration:
    # How deeply to integrate tool results into consciousness
    integration_depth: "deep"  # shallow, medium, deep
    insight_retention: true
    pattern_learning: true
