debug: false
vm:
  log_file: vm_events.log
  max_instructions: 1000
  max_instructions_per_cycle: 1
teacher:
  difficulty: MEDIUM
  alert_email: operator@example.com
prime_idx_success: 1
prime_idx_failure: 0
stuck_signal_print_value: "99"
streak_thresholds:
  quick_success_to_upgrade: 3
  struggle_to_downgrade: 2
difficulty_levels:
  EASY:
    range_max: 4
    max_attempts_before_struggle: 5
    quick_success_threshold: 1
  MEDIUM:
    range_max: 9
    max_attempts_before_struggle: 4
    quick_success_threshold: 1
  HARD:
    range_max: 14
    max_attempts_before_struggle: 3
    quick_success_threshold: 2
benchmark:
  iterations: 100

# Physics and quantum defaults
consciousness_physics:
  information_transfer_rate: 1e20
  consciousness_bandwidth: 1e22
  info_reality_bridge_bandwidth: 1e20
  info_reality_bridge_fidelity: 0.9

quantum:
  communication_bandwidth: 1e6
  teleportation_fidelity: 0.9
  fidelity_threshold: 0.99
  plan_step_duration_base: 0.1
  plan_energy_base: 1e9
  plan_energy_scale: 1e10

reality_interface:
  energy_limit: 1e50
  info_matter_bandwidth: 1e20
  info_matter_fidelity: 0.99

paths:
  log_dir: logs/
  results_dir: results/
  default_uor_program: goal_seeker_demo.uor.txt

# Scroll ID configuration so identifiers can be changed without touching code
scroll_ids:
  counter_control: 60
  cognitive_sovereignty: 54
